### ISSUE TITLE
Utilisation des goroutines accélérer le traitement des images

### ISSUE THREAD

**Issue by Lgt2x** [Lgt2x/ELP-GO#8]
Ici 1 requête <=> 1 goroutine
Il vaudrait mieux utiliser plusieurs routines (utiliser le Pool ?) par image pour accélérer le traitement

**Comment by merlou52** [comment]
utilisation de 4 goroutines par filtre pour traiter l'image fait mais n'est pas aussi efficace qu'escompté (environ 1s de gain sur une grosse image): peut-être des idées d'améliorations?
Rajouter des mutex pour éviter les collisions sur la variable image d'origine car pour le moment les routines accèdent toutes en même temps en lecture à la même variable mais pas au même pixel => pas d'erreurs pour le moment...
